#!/usr/bin/bash
# =============================================================================
# @file   root-build
# @author Derek Anderson
# @date   10.31.2024
#
# Compiles specified implementation file via root.
# =============================================================================

root -b -q BHCalPlotter.cxx++

# end =========================================================================
